export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
